config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
    get '/sign_out' => 'users/sessions#destroy'
    

  resources :users
  
  resources :noots
  resources :materias
  resources :create
  resources :lownoots
  root to: 'materias#index'
  
 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    can :manage, Noot, user_id: :user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/materium.rb
class Materium < ApplicationRecord

    def self.pessoa(lugar)
     pessoa = "você vai para "
        tudo = pessoa + lugar
    end
    def self.bimestre
      @noots = Noot.all
      escreva = @noots
    end
 
end

app/models/noot.rb
class Noot < ApplicationRecord
    def self.bimestre
        @noots = Noot.find(7)
        @noots.name

        
 
      end
end

app/models/score.rb
class Score < ApplicationRecord
    belongs_to :student
end

app/models/score_additional.rb
class ScoreAdditional < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
end

app/controllers/Noots_Controller.rb
class NootsController < ApplicationController
  before_action :set_noot, only: [:show, :lownot, :edit, :update, :destroy]

  # GET /noots
  # GET /noots.json
  include Devise::Controllers::Helpers 
  def index
       @noots = Noot.where(user_id: current_user)
  end
      
  # GET /noots/1
  # GET /noots/1.json
  def show
    
  end


  # GET /noots/new
  def new
    @noot = Noot.new
  end

  # GET /noots/1/edit
  def edit
  end

  # POST /noots
  # POST /noots.json
  def create
    @noot = Noot.new(noot_params)

    respond_to do |format|
      if @noot.save
        format.html { redirect_to @noot, notice: 'Noot was successfully created.' }
        format.json { render :show, status: :created, location: @noot }
      else
        format.html { render :new }
        format.json { render json: @noot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noots/1
  # PATCH/PUT /noots/1.json
  def update
    @noot= Noot.find(params[:id])
		noot_params =  params.require(:noot).permit(:materia, :nota_mensal, :nota_bimestral, :bimestre, :user_id)
    @noot.update(noot_params)
    redirect_to '/noots'
 
  end

  # DELETE /noots/1
  # DELETE /noots/1.json
  def destroy
    @noot.destroy
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noot
      @noot = Noot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noot_params
      params.require(:noot).permit(:materia, :nota_mensal, :nota_bimestral, :bimestre, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  before_action :authenticate_user!

 
  def after_sign_out_path_for(resource)
    noots_path
  end

  def after_sign_up_path_for(resource)
    materias_path
  end

  def after_sign_in_path_for(resource)
    materias_path
  end

  

end

app/controllers/lownoots_controller.rb
class LownootsController < ApplicationController
    def index
        
        @nootas = Noot.where("(nota_mensal + nota_bimestral) /2 <= 6")
    end
    def edit
    end



end

app/controllers/materias_controller.rb
class MateriasController < ApplicationController

    def index 
      
        @noot = Noot.new
        render layout: 'materias'
    end
    def vamo
@noots = Noot.all
    end

    def edit
      @noot = Noot.find(params[:id])
    end

    def new 
      @noot =  Noot.new

    end
    def create
      @noot = Noot.new(params[:noot])
      @noot.save
   
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lownoots_helper.rb
module LownootsHelper
end

app/helpers/materias_helper.rb
module MateriasHelper
end

app/helpers/noots_helper.rb
module NootsHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noots</title>
    <%= csrf_meta_tags %>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notas - Noots</title>
    <%= csrf_meta_tags %>
      <meta name="mobile-web-app-capable" content="yes">


<%= stylesheet_link_tag "users", media: "all", "data-turbolinks-track": 'reload' %>


 <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/lownoots.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piores Notas - Noots</title>
    <%= csrf_meta_tags %>

<%= stylesheet_link_tag "lownoots", media: "all", "data-turbolinks-track": 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/materialize.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Materialize - Noots</title>
    <%= csrf_meta_tags %>
    
<%= stylesheet_link_tag "materialize", media: "all", "data-turbolinks-track": 'reload' %>



    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/materias.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Máterias - Noots</title>
    <%= csrf_meta_tags %>
      <meta name="mobile-web-app-capable" content="yes">

<%= stylesheet_link_tag "materias", media: "all", "data-turbolinks-track": 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/noots.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notas - Noots</title>
    <%= csrf_meta_tags %>

    <meta name="mobile-web-app-capable" content="yes">


<%= stylesheet_link_tag "noots", media: "all", "data-turbolinks-track": 'reload' %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notas - Noots</title>
    <%= csrf_meta_tags %>
      <meta name="mobile-web-app-capable" content="yes">


<%= stylesheet_link_tag "users", media: "all", "data-turbolinks-track": 'reload' %>


 <%= javascript_include_tag 'user', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
   
  </body>
</html>

app/views/lownoots/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
   

   
  <script src="//code.jquery.com/mobile/1.5.0-alpha.1/jquery.mobile-1.5.0-alpha.1.min.js"></script>

    <script type="text/javascript">
        document.write('<script src="http://' + (location.host || '${1:localhost}').split(':')[0] + ':${2:35729}/livereload.js?snipver=1"></' + 'script>');
        </script>

        <!--Let browser know website is optimized for mobile-->

</head>

<body>


 

    <div id="mask"></div>

    <section class="interface">
       <section id="materias" >

            <center><h1>Escolha a matéria desejada.</h1></center>
            
            <ul id="tochoosematerias">
            
        <center>
            <% @nootas.each do |nota| %>
            <li id="piores" class="hvr-outline-out" action="nota.edit">
              <%= link_to '', nota , id:"show" %> 
              <h3 id="media"> <%= (nota.nota_mensal + nota.nota_bimestral) /2 %> </h3>
            <div id="center">
              <label><%= nota.materia %></label>
            </div>
                 
            </li>

               <% end %>
         </center>
      </ul>
       


        </section>


      
       


      
       
        
       
        
      
</section>

<div id="hideli"></div>

	<button id="burger" class="open-main-nav">
			<span class="burger"></span>
			<span class="burger-text">Menu</span>
		</button>
		<nav class="main-nav" id="main-nav">
			<ul>
				<li>
					<a href="/materias" id="first">Matérias</a>
				</li>
				<li>
					<a href="/noots">Notas</a>
				</li>
				<li>
					<a href="/lownoots">Piores Notas</a>
				</li>
			
			</ul>
		</nav>





        </body>

</html>

app/views/materias/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Máterias - Noots</title>

   
 

    <script type="text/javascript">

        $(document).ready(function(){

        $('#m1').mouseover(function() {
            $('head').append('<style>.hvr-outline2-out:before{border-color:#CC4521;}</style>');

            var valor1 = $("#m1").text();
           $("#noot_materia").val(valor1);
          
         });
        $('#m2').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#9C6E01;}</style>');

            var valor1 = $("#m2").text();
            $("#noot_materia").val(valor1);
        });
        $('#m3').mouseover(function() {
            $('head').append('<style>.hvr-outline2-out:before{border-color:#6C0863;}</style>');

            var valor1 = $("#m3").text();
            $("#noot_materia").val(valor1);
        });
        $('#m4').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#00C8C6;}</style>');

            var valor1 = $("#m4").text();
            $("#noot_materia").val(valor1);
        });
        $('#m5').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#7FC8F1;}</style>');
            var valor1 = $("#m5").text();
            $("#noot_materia").val(valor1);
        });
        $('#m6').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#5DDDD3;}</style>');

            var valor1 = $("#m6").text();
            $("#noot_materia").val(valor1);
        });
        $('#m7').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#00A5A9;}</style>');

            var valor1 = $("#m7").text();
            $("#noot_materia").val(valor1);
        });
        $('#m8').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#E48BFF;}</style>');

            var valor1 = $("#m8").text();
            $("#noot_materia").val(valor1);
        });
        $('#m9').mouseover(function() {
            $('head').append('<style>.hvr-outline2-out:before{border-color:#000000;}</style>');
            
            var valor1 = $("#m9").text();
            $("#noot_materia").val(valor1);
        });
        $('#m10').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#00B0FF;}</style>');

            var valor1 = $("#m10").text();
            $("#noot_materia").val(valor1);
        });
        $('#m11').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#86DAF1;}</style>');

            var valor1 = $("#m11").text();
            $("#noot_materia").val(valor1);
        });
        $('#m12').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#99ABFF;}</style>');

            var valor1 = $("#m12").text();
            $("#noot_materia").val(valor1);
        });
        $('#m13').mouseover(function() {
            $('head').append('<style>.hvr-outline2-out:before{border-color:#C60A1E;}</style>');
            var valor1 = $("#m13").text();
            $("#noot_materia").val(valor1);
        });
        $('#m14').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#43AB5F;}</style>');
            var valor1 = $("#m14").text();
            $("#noot_materia").val(valor1);
        });
        $('#m15').mouseover(function() {
            $('head').append('<style>.hvr-outline2-out:before{border-color:#F71C55;}</style>');
            var valor1 = $("#m15").text();
            $("#noot_materia").val(valor1);
        });
        $('#m16').mouseover(function() {
            $('head').append('<style>.hvr-outline-out:before{border-color:#FF757C;}</style>');
            var valor1 = $("#m16").text();
            $("#noot_materia").val(valor1);
        });






        });
        document.write('<script src="http://' + (location.host || '${1:localhost}').split(':')[0] + ':${2:35729}/livereload.js?snipver=1"></' + 'script>');
        </script>

        <!--Let browser know website is optimized for mobile-->

</head>

<body>


    <div id="mask"></div>
    <div id="mask2"></div>

    <section class="interface">
     
       <section id="materias" >

        <button id="burger" class="open-main-nav">
			<span class="burger"></span>
			<span class="burger-text">Menu</span>
		</button>
		<nav class="main-nav" id="main-nav">
			<ul>
				<li>
					<a href="/materias" id="first">Matérias</a>
				</li>
				<li>
					<a href="/noots">Notas</a>
				</li>
				<li>
					<a href="/lownoots">Piores Notas</a>
				</li>
			
			</ul>
		</nav>

            <center><h1>Escolha a matéria desejada.</h1></center>
            
         
          <div id="teste">
            <p class="navbar-text pull-right">
            <% if user_signed_in? %>
            Logado como: <strong><%= current_user.email %></strong>.
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

 <div>

            <ul id="tochoosematerias">
            <center>
                <li id="m1" class="hvr-outline2-out">
                    <span>Português</span></li>

                <li id="m2" class="hvr-outline-out">
                <span>Literatura</span></li>
                <li id="m3"class="hvr-outline2-out"><span>Redação</span></li>
                <li id="m4"class="hvr-outline-out"><span>Matemática</span></li>
                <li id="m5"class="hvr-outline-out"><span>Física</span></li>
                <li id="m6"class="hvr-outline-out">
                <span>Química</span></li>
                <li id="m7"class="hvr-outline-out">
                <span>Biologia</span></li>
                <li id="m8"class="hvr-outline-out">
                    <span>Sociologia</span></li>
                <li id="m9"class="hvr-outline2-out"><span>Filosofia</span></li>
                <li id="m10"class="hvr-outline-out"><span>História</span></li>
                <li id="m11"class="hvr-outline-out"><span>Geografia</span></li>
                <li id="m12"class="hvr-outline-out"><span>Inglês</span></li>
                <li id="m13"class="hvr-outline2-out"><span>Espanhol</span></li>
                <li id="m14"class="hvr-outline-out"><span>Ed.Ambiental</span></li>
                <li id="m15"class="hvr-outline2-out"><span>Ed.Física<span></li>
                <li id="m16"class="hvr-outline-out"><span>Artes</span></li>
    </center>
            </ul>
<div>

        </section>


      
       


        <center>
        <div id="pop-up">
        <div id="dentro">
        
            <center>
                <h2>Adicionar Nota</h2>
                
                
            </center>
        
        <center>
             
            <p>
                <label id="gap">
                  <input class="with-gap" name="group3" value="1"type="radio" id="one"/>
                  <span class="cyan-text text-accent-3">1º Bimestre</span>
        
                </label>
              </p>
        
              <p>
                <label id="gap2">
                  <input class="with-gap" name="group3" type="radio" value="2" id="one2"/>
                  <span class="cyan-text text-accent-3">2º Bimestre</span>
        
                </label>
              </p>
        
              <br>
              <p style="margin-left: 7px;">
                <label id="gap3">
                  <input class="with-gap" name="group3" value="3" type="radio" id="one3">
                  <span class="cyan-text text-accent-3">3º Bimestre</span>
        
                </label>
              </p>
        
              <p>
                <label id="gap4">
                  <input class="with-gap" name="group3" value="4"type="radio" id="one4"/>
                  <span class="cyan-text text-accent-3">4º Bimestre</span>
        
                </label>
              </p>
        
        
        </center>
        
        <center><div id="line_bottom"></div></center>
        
        
       
        
        
                <%= form_for(@noot) do |form| %>
        
            <div class="field1">
                <%= form.label :materia %>
                </br>
                <%= form.text_field :materia, id: :noot_materia, autocomplete: 'off' %>
                </br>
            </div>
        </br>
            <div class="field2">
                <%= form.label :nota_mensal %>
                </br>
                <%= form.number_field :nota_mensal, id: :noot_nota_mensal, autocomplete: 'off', step: :any %>
                </br>
            </div>
            <div class="field3">
                <%= form.label :nota_bimestral %>
                </br>
                <%= form.number_field :nota_bimestral, id: :noot_nota_bimestral, autocomplete: 'off', step: :any %>
                </br>
            </div>
        
            <div class="field5">
                <%= form.label :bimestre %>
                </br>
                <%= form.text_field :bimestre, id: :noot_bimestre, autocomplete: 'off' %>
                </br>
            </div>

             <div class="field4">
                <%= form.label :user_id %>
                </br>
                <%= form.number_field :user_id, id: :noot_user_id, :value => current_user.id %>

                </br>
            </div>
        </br>
        
                <%= form.submit :Salvar, class: "btn waves-effect waves-light" %>
        
        
           

                </div>  
                <% end %>
        
        </center>

      


</section>

<div id="hideli"></div>

	



        </body>

</html>

app/views/noots/edit.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Editar - Noots</title>



</head>

<body>
<!-- AREA DE MENU-->
    <section class="menu-left">

                <center><label id="logo">Noots</label></center>

                <div id="item1" >
                <a id="a1" href="/">Adicionar Notas</a>
                </div>
                <div id="item2">
                    <a id="a2" href="/noots">Médias</a>
                </div>
                <div id="item3">
                    <a id="a3" href="/lownoots">Piores Notas</a>
                </div>
        </section>
        

<section id="interface">

    <h1>Editar Nota (<%= @noot.materia %>)</h1>
        <section id="materias" > 
           
            <%= render 'form', noot: @noot %>

            <%= link_to 'Show', @noot %> |
            <%= link_to 'Back', noots_path %>
        
            </section>
    </section>

</body>
</html>

app/views/noots/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Notas - Noots</title>
    

 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
</head>

<body>
<section id="interface"> 

<div id="top">
  
    <h1 id="titulo"><center>Notas por Bimestre</center></h1>
    
  
</div>
       <section id="materias" >
       

       <table>
         <thead>
           <tr>
             <th>Materia</th>
             <th><center>Mensal</center></th>
             <th><center>Bimestral</center></th>
            
<th>
    <select id="#" class="nice-select">

        <option data-display="Bimestre">Bimestre</option>
        <option value="1">1º Bimestre</option>  
        <option>2º Bimestre</option>
        <option>3º Bimestre</option>
        <option>4º Bimestre</option>
    </select>
</th>
            
           </tr>
         </thead>

         <tbody>
           <% @noots.each do |noot| %>
             <tr id=<%= noot.id %> class="corpo">
               <td><%= noot.materia %> </td>
               <td id="nm"><center><%= noot.nota_mensal %></center></td>
               <td id="nb"><center><%= noot.nota_bimestral %></center></td>
               
               
            
             
               <td class="bimestre"><center><%= noot.bimestre %></center></td>
           

           

              
               <div id="actions">
                <td>
                  <ul id="lista">
              <li id="editar" >
                
               <%= link_to 'edit', edit_noot_path(noot), :class => "medium material-icons" %>
            
           </li>
         
              <li id="detalhes">
                 <%= link_to 'info', noot, :class => "medium material-icons" %> 
               </li>
              <li id="excluir" class="<%= noot.id %>" >
              <%= link_to 'delete', noot_path(noot), method: :delete, :class => "medium material-icons", :id => noot.id, :confirm "Gostaria de excluir esta nota?" %> 
            </li>
              </ul>
            </td>
                
            </div>
        
               </tr>
           <% end %>


         </tbody>
       </table>

       <br>
      
      <center>
      <div id="sub">  <a href="/materias" id="new">Nova nota</a> </div>
      </center>



       
      </section>
      
    </section>

  
      


		<button id="burger" class="open-main-nav">
			<span class="burger"></span>
			<span class="burger-text">Menu</span>
		</button>
		<nav class="main-nav" id="main-nav">
			<ul>
				<li>
					<a href="/materias" id="first">Matérias</a>
				</li>
				<li>
					<a href="/noots">Notas</a>
				</li>
				<li>
					<a href="/lownoots">Piores Notas</a>
				</li>
			
			</ul>
		</nav>

  </body>
</html>

app/views/noots/new.html.erb
<h1>New Noot</h1>

<%= render 'form', noot: @noot %>

<%= link_to 'Back', noots_path %>

app/views/noots/show.html.erb
<!DOCTYPE html>
<html>
<body>
<!-- AREA DE MENU-->
<section class="menu-left">

            <center><label id="logo">Noots</label></center>

            <div id="item1" >
            <a id="a1" href="/">Adicionar Notas</a>
            </div>
            <div id="item2b">
                <a id="a2b" href="/noots"> Médias </a>
            </div>
            <div id="item3">
                <a id="a3" href="/lownoots">Piores Notas</a>
            </div>
    </section>

<section id="interface">
   
<center><h1>

  <%= @noot.materia %>

</h1></center>
<section id="materias" >

  <h3 id="bimestre"><%= @noot.bimestre %>º Bimestre</h3>
  <center><div id="line"></div></center>

  


<center>
<ul id="mensal">
  <li>
    <h3 id="titulo">Nota Mensal</h3>
      <p id="circle">
        <%= @noot.nota_mensal %>
      <p>
  </li>
</ul>

<ul id="bimestral">
  <li>
  <h3 id="titulo">Nota Bimestral</h3>
  <p id="circle">
    <%= @noot.nota_bimestral %>
    <p>
  </li>
</ul>
</center>

<center>
<ul id="Média">
  <li>
  <h3 id="titulo">Média</h3>
  <p id="circle2">
    <%= (@noot.nota_mensal + @noot.nota_bimestral) / 2%>
    <p>
  </li>
</ul>
</center>


<br>
<center>
<%= link_to 'Edit', edit_noot_path(@noot) %> |
<%= link_to 'Back', noots_path %> |
<%= link_to 'Excluir', @noot, method: :delete, data: { confirm: 'Tem Certeza?' } %>

</center>

</section>

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.pass %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @user.pass %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>